### ISSUE TITLE
crucial tests and memory mismanagement

### ISSUE THREAD

**Issue by saifshaikh48** [melina7890/AI-part2#22]
Hey few quick things regarding test_keys() and test_values() --
1. Lines 122 and 132 refer to `Objects*` by accident instead of `Object*`

2. Should the `map->keys();` and `map->values();` methods return copies of the keys/values? (According to your comments on lines 104 and 129 and the test in the test_values() method the I am inclined to say yes, copies, unless I am misunderstanding.) If so then the test_keys() tests on lines 108-111 should be 
`t_true(in(nkeys, one, 2));
  t_true(in(nkeys, two, 2));
  t_false(in(nkeys, s1, 2));
  t_false(in(nkeys, s2, 2));`

P.S. after making these changes everything should work beautifully. We appreciate the quick responses

**Comment by sudopluto** [comment]
also when add() overwrites an existing value, should the existing value be deleted? right now the pointer is just lost / unspecified.

**Comment by elehman16** [comment]
Taking a look now! .... *A few minutes later* Yup good catch! I will make those changes.

**Comment by elehman16** [comment]
> also when add() overwrites an existing value, should the existing value be deleted? right now the pointer is just lost / unspecified.

So this was actually another issue raised by some other people, and we kind of just added delete statements on "Map", to kind of imply that deleting the Map/doing anything with the map doesn't delete anything. If you look at the sequence of tests here, this *might* answer your question:

String* one = new String("1");
String* not_one = new String("1");

map->add(one, s2);
map->add(not_one, s1);
t_true(map->get(one)->equals(s1));

So the variable "one" is not deleted. Now, I suppose you could argue that you aren't sure that "s2" is delete, but we use "s2" in the rest of the tests without redefining, so in a way, it implies that "s2" is not delete. Let me know if this works. I can also add some explicit tests if the current tests make you nervous (just comment sooner rather than later)!
